# Версии ПО
asterisk_version: "20-current"
freepbx_version: "17.0"
php_version: "8.3"
node_version: "18"

# Настройки сети
timezone: "Europe/Moscow"
server_ip: "172.20.10.3"
domain: "voip.local"
local_network: ["172.20.10.0/24"]

# Настройки БД
#mysql_root_password: "P@ssw0rd"
mysql_root_password: "SecureRootPass123!"
asterisk_db_user: "asterisk"
asterisk_db_password: "asterisk_123"

# Настройки FreePBX
freepbx_admin_password: "Admin@123"
freepbx_webroot: "/var/www/html/freepbx"

# Настройки SIP
sip_port: 5060
sip_tls_port: 5061
rtp_start: 10000
rtp_end: 20000

# Телефоны
sip_phones:
  - number: "100"
    name: "Operator"
    secret: "phone101"
    context: "internal"
    voicemail_pin: "1234"
    email: "andrey1@example.com"

  - number: "101"
    name: "employe1"
    secret: "phone102"
    context: "internal"
    voicemail_pin: "5678"
    email: "sergey@example.com"

  - number: "102"
    name: "test1"
    secret: "phone102"
    context: "internal"
    voicemail_pin: "9999"
    email: "andrey2@example.com"

# Очереди
queues:
  - name: "support"
    extension: "800"
    timeout: 30
    maxlen: 10
    wrapuptime: 10
    members: ["100", "102"]
    strategy: "ringall"
    announce_holdtime: yes
    announce_position: yes

  - name: "sales"
    display_name: "sales"
    extension: "801"
    timeout: 25
    maxlen: 5
    members: ["101"]
    strategy: "leastrecent"
    announce_holdtime: no
    announce_position: no

music_on_hold_class: "default"
install_music_on_hold: true

#voicemail_max_messages: 100
voicemail_max_messages: 300
voicemail_email_notification: false

IVR_EXTEN: "500"
