[voip_servers]
asterisk-server ansible_host=192.168.0.13 ansible_user=root

[voip_phones]
phone-101 ansible_host=192.168.0.13
#phone-102 ansible_host=192.168.0.14
#phone-103 ansible_host=192.168.1.15

[all:vars]
ansible_python_interpreter=/usr/bin/python3
