[modules]
autoload = yes
noload => chan_skinny.so
noload => chan_alsa.so
noload => chan_console.so
noload => chan_mgcp.so
noload => chan_ooh323.so

load => chan_sip.so
load => app_dial.so
load => app_queue.so
load => app_playback.so
load => app_verbose.so
load => app_answer.so
load => app_hangup.so
load => app_musiconhold.so
load => app_voicemail.so

load => codec_ulaw.so
load => codec_alaw.so
load => codec_gsm.so

load => format_wav.so
load => format_wav_gsm.so
load => format_gsm.so
