---
- name: Установка и настройка Asterisk + FreePBX на Debian
  hosts: voip_servers
  become: yes
  vars_files:
    - group_vars/all.yaml

  tasks:
    - name: Установка базовых пакетов
      apt:
        name:
          - wget
          - tar
          - curl
          - gnupg
          - ca-certificates
          - cron
          - build-essential
          - git
          - ufw
          - vim
        state: present
        update_cache: no

    #- name: Настройка локали
    #  locale_gen:
    #    name: ru_RU.UTF-8
    #    state: present

    - name: Установка часового пояса
      timezone:
        name: "{{ timezone }}"

    - name: Установка и запуск chrony
      apt:
        name: chrony
        state: present
      notify: restart chrony

    - name: Настройка firewall
      ufw:
        rule: "{{ item.rule }}"
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
        state: enabled
        policy: deny

      with_items:
        - { rule: allow, port: "22", proto: tcp }
        - { rule: allow, port: "80", proto: tcp }
        - { rule: allow, port: "443", proto: tcp }
        - { rule: allow, port: "{{ sip_port }}", proto: tcp }
        - { rule: allow, port: "{{ sip_port }}", proto: udp }
        - { rule: allow, port: "{{ sip_tls_port }}", proto: tcp }
        - { rule: allow, port: "{{ sip_tls_port }}", proto: udp }
        - { rule: allow, port: "{{ rtp_start }}:{{ rtp_end }}", proto: udp }
      when: ansible_facts['os_family'] == 'Debian'

    - name: Создание пользователя asterisk
      user:
        name: asterisk
        #password: 123
        shell: /bin/bash
        create_home: yes
        system: yes

    - name: Установка зависимостей для сборки Asterisk
      apt:
        name:
          - libedit-dev
          - libxml2-dev
          - libsqlite3-dev
          - libssl-dev
          - libcurl4-openssl-dev
          - libpq-dev
          - libncurses5-dev
          - libnewt-dev
          - libjansson-dev
          - libsrtp2-dev
          - libiksemel-dev
          - libvorbis-dev
          - libogg-dev
          - libasound2-dev
          - sox
          - mpg123
          - sqlite3
          - odbc-postgresql
          - unixodbc-dev
        state: present

    - name: Check asterisk download
      shell: |
        asterisk -V 2>/dev/null | head -1 | grep -o '[0-9]\+
        \.[0-9]\+\.[0-9]\+' || echo "not_installed"
      register: asterisk_installed
      changed_when: false

    - name: Скачивание Asterisk
      get_url:
        url: "https://downloads.asterisk.org/pub/telephony/asterisk/asterisk-{{ asterisk_version }}.tar.gz"
        dest: "/tmp/asterisk-{{ asterisk_version }}.tar.gz"
        mode: "0644"
      register: download_asterisk
      when: asterisk_installed == 'not_installed'

    - name: Распаковка Asterisk
      unarchive:
        src: "/tmp/asterisk-{{ asterisk_version }}.tar.gz"
        dest: /usr/src/
        remote_src: yes
        creates: "/usr/src/asterisk-{{ asterisk_version }}"
      when: asterisk_installed == 'not_installed'

    - name: Check of asterisk packets
      shell: |
        dpkg -l | grep -E 'libedit|libxml2|libsqlite3|libssl-dev|libjansson|libncurses'
      register: deps_installed

    - name: Установка зависимостей Asterisk
      shell: |
        cd "/usr/src/asterisk-20.17.0/contrib/scripts"
        ./install_prereq install || true
      args:
        executable: /bin/bash
      #ignore_errors: yes
      changed_when: false
      when: deps_installed.stdout|int < 3

    - name: Check conf asterisk
      stat:
        path: /usr/src/asterisk-20.17.0
      register: asterisk_conf

    - name: Конфигурация Asterisk
      shell: |
        cd /usr/src/asterisk-20.17.0
        ./configure --with-jansson-bundled
      args:
        chdir: /usr/src/asterisk-20.17.0

    - name: Компиляция Asterisk
      shell: |
        cd /usr/src/asterisk-20.17.0
        make -j$(nproc)
      args:
        chdir: /usr/src/asterisk-20.17.0

    - name: Установка Asterisk
      shell: |
        cd /usr/src/asterisk-20.17.0
        make install
        make config
        ldconfig
        make samples
      args:
        chdir: /usr/src/asterisk-20.17.0

    - name: Настройка пользователя Asterisk
      lineinfile:
        path: /etc/asterisk/asterisk.conf
        regexp: "^#?{{ item.key }}"
        line: "{{ item.key }} = {{ item.value }}"
      with_items:
        - { key: "runuser", value: "asterisk" }
        - { key: "rungroup", value: "asterisk" }
        - { key: "defaultlanguage", value: "ru" }
        - { key: "documentation_language", value: "ru_RU" }

    - name: Настройка прав на каталоги
      file:
        path: "{{ item }}"
        state: directory
        owner: asterisk
        group: asterisk
        mode: '0755'
        recurse: yes
      with_items:
        - /var/run/asterisk
        - /etc/asterisk
        - /var/lib/asterisk
        - /var/log/asterisk
        - /var/spool/asterisk
        - /var/spool/asterisk/monirot
        - /var/spool/asterisk/voicemail

    - name: Installing rus sound
      apt:
        name: asterisk-core-sounds-ru-wav
        state: present

    #- name: Download await music
    #  get_url:
    #    url: "https://downloads.asterisk.org/pub/telephony/sounds/asterisk-moh-opsound-wav.tar.gz"
    #    dest: /tmp/asterisk-moh.tar.gz
    #  when: install_music_on_hold | default(true)

    #- name: Unpack music
    #  unarchive:
    #    src: /tmp/asterisk-moh.tar.gz
    #    dest: /var/lib/asterisk/moh/
    #    remote_src: yes
    #    creates: /var/lib/asterisk/moh/opsound
    #  when: install_music_on_hold | default(true)

    - name: Install sounds
      become: yes
      apt:
        name: asterisk-moh-opsound-wav
        state: present

    - name: Ensure directory /etc/asterisk/pjsip.d exists
      file:
        path: /etc/asterisk/pjsip.d
        state: directory
        owner: root
        mode: '0755'

    - name: Copy pjsip.conf (SIP phones)
      template:
        src: pjsip.conf.j2
        dest: /etc/asterisk/pjsip.d/pjsip.conf
        owner: asterisk
        group: asterisk
        mode: '0640'

    - name: Set queues variable
      set_fact:
        asterisk_queues:
          - name: support
            extension: 700

    - name: Copy extensions.conf (calls)
      template:
        src: extensions.conf.j2
        dest: /etc/asterisk/extensions.conf
        owner: asterisk
        group: asterisk
        mode: '0640'

    - name: Copy queues.conf
      template:
        src: queues.conf.j2
        dest: /etc/asterisk/queues.conf
        owner: asterisk
        group: asterisk
        mode: '0640'





    - name: Copy voicemail.conf
      template:
        src: voicemail.conf.j2
        dest: /etc/asterisk/voicemail.conf
        owner: asterisk
        group: asterisk
        mode: '0640'

    - name: adding musichold.conf
      copy:
        dest: /etc/asterisk/musichold.conf
        content: |
          [default]
          mode = files
          directory = /var/lib/asterisk/moh/opsound
          random = yes
        owner: asterisk
        group: asterisk
        mode: '0640'

    - name: Adding cdr.conf (recording)
      copy:
        dest: /etc/asterisk/cdr.conf
        content: |
          [general]
          enable = yes

          [sqlite]
          usegmtime = yes
        owner: asterisk
        group: asterisk
        mode: '0640'

    - name: Adding systemd Service
      copy:
        dest: /etc/systemd/system/asterisk.service
        content: |
          [Unit]
          Description=Asterisk PBX
          After=network.target

          [Service]
          Type=forking
          User=asterisk
          Group=asterisk
          ExecStart=/usr/sbin/asterisk -f
          ExecReload=/usr/sbin/asterisk -rx 'core reload'
          ExecStop=/usr/sbin/asterisk -rx 'core stop now'
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reloading systemd
      systemd:
        daemon_reload: yes



    - name: Настройка автоматического запуска
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - asterisk

    #- name: reload asterisk
    #  shell: |
    #    asterisk -rx "core reload"

---
- name: Установка и настройка Asterisk
  hosts: asterisk
  become: yes
  vars:
    phones:
      - number: "101"
        password: "1111"
        name: "Телефон 1"
      - number: "102"
        password: "2222"
        name: "Телефон 2"
      - number: "103"
        password: "3333"
        name: "Телефон 3"
    
    queues:
      - name: "support"
        extension: "200"
        members: ["101", "102"]
      - name: "sales"
        extension: "201"
        members: ["103"]

  tasks:
    # 1. Установка Asterisk (работает на Ubuntu 20.04/22.04)
    - name: Обновить apt кеш
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Установить Asterisk и зависимости
      apt:
        name:
          - asterisk
          - asterisk-core-sounds-ru-wav
          - asterisk-moh-opsound-wav
        state: present
      when: ansible_os_family == 'Debian'

    # 2. Создать базовые конфиги
    - name: Создать extensions.conf
      template:
        src: templates/extensions.conf.j2
        dest: /etc/asterisk/extensions.conf
        owner: asterisk
        group: asterisk
        mode: '0644'

    - name: Создать sip.conf
      template:
        src: templates/sip.conf.j2
        dest: /etc/asterisk/sip.conf
        owner: asterisk
        group: asterisk
        mode: '0644'

    - name: Создать queues.conf
      template:
        src: templates/queues.conf.j2
        dest: /etc/asterisk/queues.conf
        owner: asterisk
        group: asterisk
        mode: '0644'

    # 3. Создать modules.conf (важно!)
    - name: Создать modules.conf
      copy:
        content: |
          [modules]
          autoload = yes
          noload => chan_skinny.so
          noload => chan_alsa.so
          noload => chan_console.so
          noload => chan_mgcp.so
          noload => chan_ooh323.so
          load => chan_sip.so
          load => app_queue.so
          load => app_musiconhold.so
          load => codec_ulaw.so
          load => codec_alaw.so
          load => codec_gsm.so
          load => format_wav.so
          load => format_wav_gsm.so
        dest: /etc/asterisk/modules.conf
        owner: asterisk
        group: asterisk
        mode: '0644'

    # 4. Настроить музыку на удержании
    - name: Настроить musiconhold.conf
      copy:
        content: |
          [general]
          [default]
          mode=files
          directory=/var/lib/asterisk/moh
        dest: /etc/asterisk/musiconhold.conf
        owner: asterisk
        group: asterisk

    # 5. Скачать музыку для удержания (если нет)
    - name: Создать директорию для музыки
      file:
        path: /var/lib/asterisk/moh
        state: directory
        owner: asterisk
        group: asterisk

    - name: Скачать тестовую музыку для удержания
      get_url:
        url: https://www.soundjay.com/communication/sounds/phone-call-1.wav
        dest: /var/lib/asterisk/moh/sample.wav
        mode: '0644'
      when: not ansible_check_mode

    # 6. Настроить права
    - name: Настроить владельца для конфигов
      file:
        path: /etc/asterisk
        owner: asterisk
        group: asterisk
        recurse: yes

    # 7. Открыть порты в firewall
    - name: Установить UFW если нет
      apt:
        name: ufw
        state: present
      when: ansible_os_family == 'Debian'

    - name: Включить UFW
      ufw:
        state: enabled
        direction: incoming
        policy: deny

    - name: Открыть порт SSH
      ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: Открыть порт SIP
      ufw:
        rule: allow
        port: '5060'
        proto: udp

    - name: Открыть порты RTP
      ufw:
        rule: allow
        port: '10000:20000'
        proto: udp

    # 8. Перезапустить Asterisk
    - name: Перезапустить Asterisk
      systemd:
        name: asterisk
        state: restarted
        enabled: yes

    # 9. Проверить работу
    - name: Проверить статус Asterisk
      command: systemctl status asterisk
      register: asterisk_status
      changed_when: false

    - name: Показать статус
      debug:
        msg: "Asterisk статус: {{ asterisk_status.stdout_lines | join('\n') }}"
