; НОВОЕЕЕ
[general]
persistentmembers = yes

[support]
musicclass = default
strategy = ringall
timeout = 30
retry = 5
maxlen = 10
announce-frequency = 30
announce-position = yes

member => SIP/101
member => SIP/102
[sales]
musicclass = default
strategy = ringall
timeout = 30
retry = 5
maxlen = 10
announce-frequency = 30
announce-position = yes

member => SIP/103



