[general]
context = phones
udpbindaddr = 0.0.0.0:5060
;transport = udp
; Отключаем ненужные кодеки
;disallow = all
;allow = ulaw
;allow = alaw

[101]
type = friend
;username = 101
secret = 1111
host = 172.20.10.3
context = internal
;callerid = "Телефон 1" <101>
qualify = yes
qualifyfreq = 60
;dtmfmode = rfc2833
;canreinvite = no
insecure = port,invite
;nat = force_rport,comedia
[102]
type = friend
;username = 102
secret = 2222
host = 172.20.10.2
context = internal
;callerid = "Телефон 2" <102>
qualify = yes
qualifyfreq = 60
;dtmfmode = rfc2833
;canreinvite = no
insecure = port,invite
;nat = force_rport,comedia
[103]
type = friend
;username = 103
secret = 3333
host = 172.20.10.2
context = phones
;callerid = "Телефон 3" <103>
qualify = yes
qualifyfreq = 60
;dtmfmode = rfc2833
;canreinvite = no
insecure = port,invite
;nat = force_rport,comedia
